name: GitHub Actions for Fastlane
on: [push]
jobs:
  build:
    runs-on: macos-13
    name: Run Fastlane Sample
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
      - run: xcodebuild -version
      - run: bundle install
      - run: bundle exec fastlane hello_fastlane

